// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseRestEntity.proto

package com.xiaogua.comments.bean.common;

/**
 * <pre>
 * 每次响应的头信息
 * </pre>
 */
public class RespHeader {

    /**
     * 返回码
     */
    int code;

    /**
     * 消息
     */
    String msg;

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public RespHeader() {
    }

    public RespHeader(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }
}

